apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: overprovisioning
description: Priority class used by overprovisioning.
preemptionPolicy: PreemptLowerPriority
globalDefault: false
value: -1
